require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LocalizacaosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Localizacao. As you add validations to Localizacao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LocalizacaosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all localizacaos as @localizacaos" do
      localizacao = Localizacao.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:localizacaos)).to eq([localizacao])
    end
  end

  describe "GET #show" do
    it "assigns the requested localizacao as @localizacao" do
      localizacao = Localizacao.create! valid_attributes
      get :show, {:id => localizacao.to_param}, valid_session
      expect(assigns(:localizacao)).to eq(localizacao)
    end
  end

  describe "GET #new" do
    it "assigns a new localizacao as @localizacao" do
      get :new, {}, valid_session
      expect(assigns(:localizacao)).to be_a_new(Localizacao)
    end
  end

  describe "GET #edit" do
    it "assigns the requested localizacao as @localizacao" do
      localizacao = Localizacao.create! valid_attributes
      get :edit, {:id => localizacao.to_param}, valid_session
      expect(assigns(:localizacao)).to eq(localizacao)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Localizacao" do
        expect {
          post :create, {:localizacao => valid_attributes}, valid_session
        }.to change(Localizacao, :count).by(1)
      end

      it "assigns a newly created localizacao as @localizacao" do
        post :create, {:localizacao => valid_attributes}, valid_session
        expect(assigns(:localizacao)).to be_a(Localizacao)
        expect(assigns(:localizacao)).to be_persisted
      end

      it "redirects to the created localizacao" do
        post :create, {:localizacao => valid_attributes}, valid_session
        expect(response).to redirect_to(Localizacao.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved localizacao as @localizacao" do
        post :create, {:localizacao => invalid_attributes}, valid_session
        expect(assigns(:localizacao)).to be_a_new(Localizacao)
      end

      it "re-renders the 'new' template" do
        post :create, {:localizacao => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested localizacao" do
        localizacao = Localizacao.create! valid_attributes
        put :update, {:id => localizacao.to_param, :localizacao => new_attributes}, valid_session
        localizacao.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested localizacao as @localizacao" do
        localizacao = Localizacao.create! valid_attributes
        put :update, {:id => localizacao.to_param, :localizacao => valid_attributes}, valid_session
        expect(assigns(:localizacao)).to eq(localizacao)
      end

      it "redirects to the localizacao" do
        localizacao = Localizacao.create! valid_attributes
        put :update, {:id => localizacao.to_param, :localizacao => valid_attributes}, valid_session
        expect(response).to redirect_to(localizacao)
      end
    end

    context "with invalid params" do
      it "assigns the localizacao as @localizacao" do
        localizacao = Localizacao.create! valid_attributes
        put :update, {:id => localizacao.to_param, :localizacao => invalid_attributes}, valid_session
        expect(assigns(:localizacao)).to eq(localizacao)
      end

      it "re-renders the 'edit' template" do
        localizacao = Localizacao.create! valid_attributes
        put :update, {:id => localizacao.to_param, :localizacao => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested localizacao" do
      localizacao = Localizacao.create! valid_attributes
      expect {
        delete :destroy, {:id => localizacao.to_param}, valid_session
      }.to change(Localizacao, :count).by(-1)
    end

    it "redirects to the localizacaos list" do
      localizacao = Localizacao.create! valid_attributes
      delete :destroy, {:id => localizacao.to_param}, valid_session
      expect(response).to redirect_to(localizacaos_url)
    end
  end

end
